# Generated by Django 4.2.6 on 2024-01-02 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0003_alter_data_sensor_air_humidity_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_actuator',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.node'),
        ),
        migrations.AlterField(
            model_name='data_sensor',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.node'),
        ),
    ]
