# Generated by Django 4.2.6 on 2024-01-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0004_alter_data_actuator_id_alter_data_sensor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuator',
            name='status_motor_1',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='actuator',
            name='status_motor_2',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='actuator',
            name='status_motor_3',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='actuator',
            name='status_motor_4',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='actuator',
            name='status_node',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='status_air_humidity_1',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='status_air_humidity_2',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='status_air_temperature_1',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='status_air_temperature_2',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='status_light_intensity_1',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='status_light_intensity_2',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='status_node',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='status_soil_moisture_1',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='status_soil_moisture_2',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
