# Generated by Django 4.2.6 on 2024-01-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0005_alter_actuator_status_motor_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuator',
            name='name_motor_1',
            field=models.CharField(default='Pump', max_length=30),
        ),
        migrations.AlterField(
            model_name='actuator',
            name='name_motor_2',
            field=models.CharField(default='Lamp', max_length=30),
        ),
        migrations.AlterField(
            model_name='actuator',
            name='name_motor_3',
            field=models.CharField(default='Fan ', max_length=30),
        ),
    ]
